### ISSUE TITLE
#16 - GAME MATCHING - FRONTEND

### ISSUE THREAD

**Issue by ricardomart26** [isousa42/ft_Transcendence#31]
The aim is to create the logic for the Game Matching. 

At the moment there is a "Start Game" button in the homepage that has no function associated. When this button is pressed, the frontend should make a request to the backend (GET) to receive the opponent information. This information should update the Opponent component. The frontend should wait for a response, in case there is no other user to make the match.

**Tasks:**

- [ ] Create the fetch with GET method
- [ ] Update the Opponent component with the information received
- [ ] Redirect the user to the Game Page
