### ISSUE TITLE
#17 - GAME MATCHING - BACKEND

### ISSUE THREAD

**Issue by isousa42** [isousa42/ft_Transcendence#33]
The aim is to create the logic for the Game Matching.

When the Start Game button in the Homepage is pressed, the frontend will make a request to make a match with other player, so a new game can be started. For this, the logic in the backend should be created, so it is possible to connect two Opponents. After the match is made, the backend should send the Opponent information to the frontend.

**Suggestion:** Set a variable at -1 when there is no user waiting for the match. When a user is waiting, this variable should be updated with the user ID. When the second player arrives and it is linked with the other user, the variable returns to the value -1.

**Tasks:**
- [ ] Create a Game Matching endpoint
- [ ] Create the logic to make the match between two users
- [ ] Send the response back to the frontend with the Opponent information
