### ISSUE TITLE
#18 - CREATE GAME COMPONENT + UPDATE OPPONENT COMPONENT

### ISSUE THREAD

**Issue by isousa42** [isousa42/ft_Transcendence#34]
The aim is to create the React component for the Game and update the Opponent component after the START GAME button is pressed. 

After the START GAME button is pressed, the frontend will ask the opponent information to the backend. When the button is pressed, the Maps component should be updated with the Game component (that should be created) and the Random component should be updated with a Player component that will handle the Opponent information received from backend. While the frontend is waiting for the backend answer, a warning must be displayed in the game component.

**Tasks:**

- [ ] Create the Game component
- [ ] Create the Random component
- [ ] Create the waiting warning
- [ ] Update the Game component to play the game
- [ ] Update the Random component for the Player component with Opponent component
